"""Ark code-quality metrics and deterministic hotspot reporting.

Metrics are advisory review signals, not a quality score or an absolute gate.
"""

from __future__ import annotations

import json
import math
import re
import subprocess
from dataclasses import asdict, dataclass
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python 3.10 on supported development hosts
    import tomli as tomllib  # type: ignore[no-redef]

try:
    from .structure import compiler_import_graph
except ImportError:  # manager.py executes with scripts/ on sys.path
    from quality.structure import compiler_import_graph


SCHEMA_VERSION = 1
BASELINE_MARKER = "# CQ-13 metrics baseline (generated by manager.py quality report --write-baseline)"
FN_START_RE = re.compile(r"^\s*(pub\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(")
THIN_WRAPPER_HEAD_RE = re.compile(
    r"^(?:pub\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*)\)\s*(?:->\s*[^{]+)?\s*\{?\s*$"
)
BRANCH_RE = re.compile(r"\b(if|for|while|match)\b|&&|\|\||=>")
TODO_RE = re.compile(r"\b(?:TODO|FIXME)\b")
SUPPRESSION_RE = re.compile(r"lint:\s*(?:disable|allow)|noqa|nolint", re.I)
CALL_RE = re.compile(
    r"^(?:return\s+)?([A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*)\s*\((.*)\)\s*;?$"
)
METRIC_NAMES = (
    "file_lines",
    "function_lines",
    "parameters",
    "nesting_depth",
    "complexity",
    "fan_in",
    "fan_out",
    "public_functions",
    "thin_wrappers",
    "lines_ge_120",
    "lines_ge_200",
    "todo_fixme",
    "lint_suppressions",
    "churn",
    "dependency_centrality",
)


@dataclass(frozen=True)
class Distribution:
    count: int
    p50: float
    p75: float
    p90: float
    p95: float
    max: float


@dataclass(frozen=True)
class FunctionMetric:
    path: str
    symbol: str
    line: int
    line_count: int
    parameters: int
    max_nesting_depth: int
    complexity: int
    is_public: bool
    is_thin_wrapper: bool


@dataclass(frozen=True)
class FileMetric:
    path: str
    line_count: int
    public_functions: int
    thin_wrappers: int
    lines_ge_120: int
    lines_ge_200: int
    todo_fixme: int
    lint_suppressions: int
    fan_in: int
    fan_out: int
    churn: int | None
    dependency_centrality: float


@dataclass(frozen=True)
class Hotspot:
    rank: int
    path: str
    symbol: str
    score: float
    complexity: int
    churn: int | None
    fan_in: int
    fan_out: int
    reason_signals: tuple[str, ...]


@dataclass(frozen=True)
class MetricsReport:
    files: tuple[FileMetric, ...]
    functions: tuple[FunctionMetric, ...]
    distributions: dict[str, Distribution]
    hotspots: tuple[Hotspot, ...]
    churn_available: bool

    def to_dict(self) -> dict[str, object]:
        return {
            "schema_version": SCHEMA_VERSION,
            "status": "pass",
            "purpose": "advisory hotspot priority; not a code-quality score",
            "churn_available": self.churn_available,
            "summary": {
                "files": len(self.files),
                "functions": len(self.functions),
                "hotspots": len(self.hotspots),
            },
            "distributions": {
                name: asdict(self.distributions[name]) for name in sorted(self.distributions)
            },
            "files": [asdict(item) for item in self.files],
            "hotspots": [asdict(item) for item in self.hotspots],
        }


def sanitize_ark_lines(text: str) -> list[str]:
    """Remove strings and comments while preserving code positions and braces."""
    output: list[str] = []
    in_block_comment = False
    for raw in text.splitlines():
        chars = list(raw)
        index = 0
        quote = ""
        while index < len(chars):
            if in_block_comment:
                if index + 1 < len(chars) and chars[index] == "*" and chars[index + 1] == "/":
                    chars[index] = chars[index + 1] = " "
                    in_block_comment = False
                    index += 2
                else:
                    chars[index] = " "
                    index += 1
                continue
            if quote:
                if chars[index] == "\\" and index + 1 < len(chars):
                    chars[index] = chars[index + 1] = " "
                    index += 2
                    continue
                if chars[index] == quote:
                    quote = ""
                chars[index] = " "
                index += 1
                continue
            if index + 1 < len(chars) and chars[index] == "/" and chars[index + 1] == "/":
                for tail in range(index, len(chars)):
                    chars[tail] = " "
                break
            if index + 1 < len(chars) and chars[index] == "/" and chars[index + 1] == "*":
                chars[index] = chars[index + 1] = " "
                in_block_comment = True
                index += 2
                continue
            if chars[index] in {'"', "'"}:
                quote = chars[index]
                chars[index] = " "
            index += 1
        output.append("".join(chars))
    return output


def _strip_line_comment(line: str) -> str:
    in_string = False
    quote = ""
    index = 0
    while index < len(line):
        char = line[index]
        if in_string:
            if char == "\\" and index + 1 < len(line):
                index += 2
                continue
            if char == quote:
                in_string = False
            index += 1
            continue
        if char in {'"', "'"}:
            in_string = True
            quote = char
            index += 1
            continue
        if char == "/" and index + 1 < len(line) and line[index + 1] == "/":
            return line[:index].rstrip()
        index += 1
    return line.rstrip()


def _parameter_count(signature: str) -> int:
    start = signature.find("(")
    if start < 0:
        return 0
    depth = 0
    pieces = 0
    has_token = False
    for char in signature[start + 1 :]:
        if char == "(" or char in "[{":
            depth += 1
        elif char == ")":
            if depth == 0:
                break
            depth -= 1
        elif char in "]}":
            depth = max(0, depth - 1)
        elif char == "," and depth == 0:
            pieces += 1
        elif not char.isspace():
            has_token = True
    return pieces + 1 if has_token else 0


def _argument_names(arguments: str) -> list[str]:
    names: list[str] = []
    depth = 0
    current: list[str] = []
    for char in arguments:
        if char in "([{":
            depth += 1
        elif char in ")]}":
            depth = max(0, depth - 1)
        if char == "," and depth == 0:
            token = "".join(current).strip()
            if token:
                names.append(token.split(".", 1)[0].strip())
            current = []
            continue
        current.append(char)
    token = "".join(current).strip()
    if token:
        names.append(token.split(".", 1)[0].strip())
    return names


def _thin_wrapper_lines(code_lines: list[str]) -> set[int]:
    """Return legacy-ratchet-compatible wrapper locations from sanitized code."""
    findings: set[int] = set()
    index = 0
    while index < len(code_lines):
        header = code_lines[index].strip()
        match = THIN_WRAPPER_HEAD_RE.match(header)
        if not match:
            index += 1
            continue
        name = match.group(1)
        parameters = [
            part.split(":", 1)[0].removeprefix("mut ").strip()
            for part in match.group(2).split(",")
            if part.strip()
        ]
        opened = "{" in header
        body_index = index + 1
        if not opened:
            while body_index < len(code_lines) and not code_lines[body_index].strip():
                body_index += 1
            if body_index >= len(code_lines) or "{" not in code_lines[body_index]:
                index += 1
                continue
            body_index += 1
        depth = 1
        statements: list[str] = []
        while body_index < len(code_lines) and depth > 0:
            code = code_lines[body_index]
            depth += code.count("{") - code.count("}")
            if depth > 0:
                statement = code.strip()
                if statement and statement != "}":
                    statements.append(statement.rstrip(";").strip())
            body_index += 1
        if len(statements) == 1:
            call = CALL_RE.match(statements[0])
            if call and call.group(1) != name and _argument_names(call.group(2)) == parameters:
                findings.add(index + 1)
        index = body_index if body_index > index else index + 1
    return findings


def scan_ark_source(path: str, text: str) -> tuple[FileMetric, list[FunctionMetric]]:
    raw_lines = text.splitlines()
    code_lines = sanitize_ark_lines(text)
    # The count is an existing ratchet. Preserve its historical recognition
    # boundary while the richer scanner uses fully sanitized lines elsewhere.
    thin_wrapper_lines = _thin_wrapper_lines([_strip_line_comment(line) for line in raw_lines])
    functions: list[FunctionMetric] = []
    index = 0
    while index < len(code_lines):
        match = FN_START_RE.match(code_lines[index])
        if not match:
            index += 1
            continue
        start = index
        signature_lines = [code_lines[index].strip()]
        while "{" not in " ".join(signature_lines) and index + 1 < len(code_lines):
            index += 1
            signature_lines.append(code_lines[index].strip())
        signature = " ".join(signature_lines)
        depth = 0
        opened = False
        maximum_depth = 0
        complexity = 1
        end = index
        while end < len(code_lines):
            line = code_lines[end]
            complexity += len(BRANCH_RE.findall(line))
            for char in line:
                if char == "{":
                    depth += 1
                    opened = True
                    maximum_depth = max(maximum_depth, depth)
                elif char == "}":
                    depth -= 1
            if opened and depth <= 0:
                break
            end += 1
        function_text = "\n".join(code_lines[start : end + 1])
        body_start = function_text.find("{")
        body_end = function_text.rfind("}")
        body_text = function_text[body_start + 1 : body_end] if body_end > body_start else ""
        functions.append(
            FunctionMetric(
                path=path,
                symbol=match.group(2),
                line=start + 1,
                line_count=end - start + 1,
                parameters=_parameter_count(signature),
                max_nesting_depth=max(0, maximum_depth - 1),
                complexity=complexity,
                is_public=bool(match.group(1)),
                is_thin_wrapper=start + 1 in thin_wrapper_lines,
            )
        )
        index = max(index + 1, end + 1)

    file_metric = FileMetric(
        path=path,
        line_count=len(raw_lines),
        public_functions=sum(item.is_public for item in functions),
        thin_wrappers=sum(item.is_thin_wrapper for item in functions),
        lines_ge_120=sum(len(line) >= 120 for line in raw_lines),
        lines_ge_200=sum(len(line) >= 200 for line in raw_lines),
        todo_fixme=sum(bool(TODO_RE.search(line)) for line in raw_lines),
        lint_suppressions=sum(bool(SUPPRESSION_RE.search(line)) for line in raw_lines),
        fan_in=0,
        fan_out=0,
        churn=None,
        dependency_centrality=0.0,
    )
    return file_metric, functions


def _distribution(values: list[int | float]) -> Distribution:
    if not values:
        return Distribution(0, 0, 0, 0, 0, 0)
    ordered = sorted(float(value) for value in values)

    def percentile(percent: int) -> float:
        index = max(0, math.ceil((percent / 100) * len(ordered)) - 1)
        return ordered[index]

    return Distribution(len(ordered), percentile(50), percentile(75), percentile(90), percentile(95), ordered[-1])


def _git_churn(root: Path, paths: set[str]) -> dict[str, int] | None:
    if not (root / ".git").exists():
        return None
    shallow = subprocess.run(
        ["git", "rev-parse", "--is-shallow-repository"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
    )
    if shallow.returncode != 0 or shallow.stdout.strip() == "true":
        return None
    history = subprocess.run(
        ["git", "log", "--format=", "--name-only", "--", "src/compiler"],
        cwd=root,
        capture_output=True,
        text=True,
        check=False,
        timeout=60,
    )
    if history.returncode != 0:
        return None
    counts = {path: 0 for path in paths}
    for line in history.stdout.splitlines():
        if line in counts:
            counts[line] += 1
    return counts


def collect_metrics(root: Path) -> MetricsReport:
    compiler_root = root / "src/compiler"
    scanned: list[tuple[FileMetric, list[FunctionMetric]]] = []
    for source in sorted(compiler_root.rglob("*.ark")):
        if source.is_file():
            rel = str(source.relative_to(root))
            scanned.append(scan_ark_source(rel, source.read_text(encoding="utf-8")))

    graph = compiler_import_graph(root)
    rel_graph = {
        str(path.relative_to(root)): [str(dep.relative_to(root)) for dep in dependencies]
        for path, dependencies in graph.items()
    }
    fan_in = {path: 0 for path in rel_graph}
    for dependencies in rel_graph.values():
        for dependency in dependencies:
            fan_in[dependency] = fan_in.get(dependency, 0) + 1
    churn = _git_churn(root, set(rel_graph))

    files: list[FileMetric] = []
    functions: list[FunctionMetric] = []
    for metric, file_functions in scanned:
        incoming = fan_in.get(metric.path, 0)
        outgoing = len(rel_graph.get(metric.path, []))
        centrality = round(math.log1p(incoming) + math.log1p(outgoing), 6)
        files.append(
            FileMetric(
                **{
                    **asdict(metric),
                    "fan_in": incoming,
                    "fan_out": outgoing,
                    "churn": churn.get(metric.path, 0) if churn is not None else None,
                    "dependency_centrality": centrality,
                }
            )
        )
        functions.extend(file_functions)

    distributions = {
        "file_lines": _distribution([item.line_count for item in files]),
        "function_lines": _distribution([item.line_count for item in functions]),
        "parameters": _distribution([item.parameters for item in functions]),
        "nesting_depth": _distribution([item.max_nesting_depth for item in functions]),
        "complexity": _distribution([item.complexity for item in functions]),
        "fan_in": _distribution([item.fan_in for item in files]),
        "fan_out": _distribution([item.fan_out for item in files]),
        "public_functions": _distribution([item.public_functions for item in files]),
        "thin_wrappers": _distribution([item.thin_wrappers for item in files]),
        "lines_ge_120": _distribution([item.lines_ge_120 for item in files]),
        "lines_ge_200": _distribution([item.lines_ge_200 for item in files]),
        "todo_fixme": _distribution([item.todo_fixme for item in files]),
        "lint_suppressions": _distribution([item.lint_suppressions for item in files]),
        "churn": _distribution([item.churn for item in files if item.churn is not None]),
        "dependency_centrality": _distribution([item.dependency_centrality for item in files]),
    }
    files_by_path = {item.path: item for item in files}
    candidates: list[tuple[float, FunctionMetric, tuple[str, ...]]] = []
    for function in functions:
        file_metric = files_by_path[function.path]
        churn_value = file_metric.churn or 0
        score = round(
            (1 + math.log1p(function.complexity))
            * (1 + math.log1p(churn_value))
            * (1 + file_metric.dependency_centrality),
            6,
        )
        reasons: list[str] = []
        if function.complexity >= distributions["complexity"].p95:
            reasons.append("complexity>=p95")
        if distributions["nesting_depth"].p95 > 0 and function.max_nesting_depth >= distributions["nesting_depth"].p95:
            reasons.append("nesting>=p95")
        if function.line_count >= distributions["function_lines"].p95:
            reasons.append("function_lines>=p95")
        if distributions["fan_in"].p95 > 0 and file_metric.fan_in >= distributions["fan_in"].p95:
            reasons.append("fan_in>=p95")
        if distributions["fan_out"].p95 > 0 and file_metric.fan_out >= distributions["fan_out"].p95:
            reasons.append("fan_out>=p95")
        if file_metric.churn is None:
            reasons.append("churn=unknown")
        elif file_metric.churn >= distributions["churn"].p95:
            reasons.append("churn>=p95")
        candidates.append((score, function, tuple(reasons or ("combined-signal",))))
    candidates.sort(key=lambda item: (-item[0], item[1].path, item[1].line, item[1].symbol))
    hotspots = tuple(
        Hotspot(
            rank=rank,
            path=function.path,
            symbol=function.symbol,
            score=score,
            complexity=function.complexity,
            churn=files_by_path[function.path].churn,
            fan_in=files_by_path[function.path].fan_in,
            fan_out=files_by_path[function.path].fan_out,
            reason_signals=reasons,
        )
        for rank, (score, function, reasons) in enumerate(candidates[:50], 1)
    )
    return MetricsReport(tuple(files), tuple(functions), distributions, hotspots, churn is not None)


def render_metrics_text(report: MetricsReport) -> str:
    lines = [
        "Ark code-quality metrics (advisory hotspot priority; not a quality score)",
        f"files={len(report.files)} functions={len(report.functions)} churn={'available' if report.churn_available else 'unknown'}",
        "",
        "metric distributions:",
    ]
    for name in sorted(report.distributions):
        dist = report.distributions[name]
        lines.append(
            f"  {name}: count={dist.count} p50={dist.p50:g} p75={dist.p75:g} "
            f"p90={dist.p90:g} p95={dist.p95:g} max={dist.max:g}"
        )
    lines.extend(("", "top hotspots:"))
    for item in report.hotspots[:20]:
        churn = "unknown" if item.churn is None else str(item.churn)
        lines.append(
            f"  {item.rank}. {item.path}:{item.symbol} score={item.score:g} "
            f"complexity={item.complexity} churn={churn} fan_in={item.fan_in} "
            f"fan_out={item.fan_out} signals={','.join(item.reason_signals)}"
        )
    return "\n".join(lines)


def _baseline_metrics(path: Path) -> dict[str, dict[str, float]]:
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    metrics = data.get("metrics", {})
    required = {"count", "p50", "p75", "p90", "p95", "max"}
    for name in METRIC_NAMES:
        if name not in metrics or required - metrics[name].keys():
            raise ValueError(f"baseline metric {name} is missing required keys")
    return metrics


def validate_metrics_baseline(path: Path) -> None:
    _baseline_metrics(path)


def _tracking_issue_exists(root: Path, issue: int) -> bool:
    return any(
        any((root / state).glob(f"{issue}-*.md"))
        for state in ("issues/open", "issues/done")
    )


def write_metrics_baseline(root: Path, report: MetricsReport, issue: int | None, reason: str | None) -> None:
    path = root / "docs/data/ark-code-quality-baseline.toml"
    path.parent.mkdir(parents=True, exist_ok=True)
    previous: dict[str, dict[str, float]] = {}
    try:
        previous = _baseline_metrics(path)
    except (OSError, ValueError, tomllib.TOMLDecodeError):
        pass
    current = {name: asdict(report.distributions[name]) for name in METRIC_NAMES}
    increases = [
        name
        for name, values in current.items()
        if name not in previous or any(float(values[key]) > float(previous[name][key]) for key in values)
    ]
    if increases:
        if issue is None or not reason:
            raise ValueError("baseline creation/increase requires --issue and --reason")
        if not _tracking_issue_exists(root, issue):
            raise ValueError(f"tracking issue {issue} does not exist")
    original = path.read_text(encoding="utf-8") if path.is_file() else ""
    prefix = original.split(BASELINE_MARKER, 1)[0].rstrip() + "\n\n"
    metadata = [
        BASELINE_MARKER,
        f"metrics_baseline_issue = {issue or 0}",
        f"metrics_baseline_reason = {json.dumps(reason or 'no increases', ensure_ascii=False)}",
    ]
    for name in METRIC_NAMES:
        metadata.append("")
        metadata.append(f"[metrics.{name}]")
        values = current[name]
        for key in ("count", "p50", "p75", "p90", "p95", "max"):
            value = values[key]
            rendered = str(int(value)) if float(value).is_integer() else f"{value:.6f}".rstrip("0")
            metadata.append(f"{key} = {rendered}")
    path.write_text(prefix + "\n".join(metadata) + "\n", encoding="utf-8")


def run_metrics_report(
    root: Path,
    json_output: bool = False,
    output: str | None = None,
    write_baseline: bool = False,
    issue: int | None = None,
    reason: str | None = None,
) -> int:
    try:
        report = collect_metrics(root)
        baseline = root / "docs/data/ark-code-quality-baseline.toml"
        if write_baseline:
            write_metrics_baseline(root, report, issue, reason)
        else:
            validate_metrics_baseline(baseline)
        payload = json.dumps(report.to_dict(), ensure_ascii=False, sort_keys=True)
        if output:
            destination = root / output if not Path(output).is_absolute() else Path(output)
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(payload + "\n", encoding="utf-8")
        print(payload if json_output else render_metrics_text(report))
        return 0
    except (OSError, ValueError, subprocess.SubprocessError, tomllib.TOMLDecodeError) as exc:
        if json_output:
            print(json.dumps({
                "schema_version": SCHEMA_VERSION,
                "status": "fail",
                "summary": {"errors": 1, "warnings": 0, "advisories": 0},
                "findings": [{"message": str(exc)}],
            }, ensure_ascii=False, sort_keys=True))
        else:
            print(f"metrics collector: FAIL: {exc}")
        return 1
