#!/usr/bin/env bash
# Validates that all files listed in .generated-files have ownership banners
# and that no unlisted files claim to be generated.
set -euo pipefail

ROOT="${1:-$(git rev-parse --show-toplevel)}"
MANIFEST="$ROOT/.generated-files"
ERRORS=0

if [[ ! -f "$MANIFEST" ]]; then
    echo "ERROR: .generated-files manifest not found at $MANIFEST"
    exit 1
fi

echo "Checking generated file boundaries..."

# Parse manifest entries (skip comments and blank lines)
declared_files=()
while IFS='|' read -r path _generator _command; do
    path=$(echo "$path" | xargs)  # trim whitespace
    [[ -z "$path" || "$path" == \#* ]] && continue
    declared_files+=("$path")
done < "$MANIFEST"

# Check 1: all declared files exist
for f in "${declared_files[@]}"; do
    full="$ROOT/$f"
    if [[ ! -f "$full" ]]; then
        echo "  MISSING: $f (declared in .generated-files but does not exist)"
        ((ERRORS++)) || true
    fi
done

# Check 2: all declared files have a generation banner
for f in "${declared_files[@]}"; do
    full="$ROOT/$f"
    [[ ! -f "$full" ]] && continue
    # Check first 5 lines for "generated" or "do not edit"
    if ! head -5 "$full" 2>/dev/null | grep -qi "generated\|do not edit\|auto-generated"; then
        echo "  NO BANNER: $f (listed in .generated-files but lacks generation banner)"
        ((ERRORS++)) || true
    fi
done

# Check 3: look for files that claim to be generated but aren't in manifest
while IFS= read -r -d '' file; do
    rel="${file#$ROOT/}"
    # Check if this file is in the manifest
    found=false
    for df in "${declared_files[@]}"; do
        if [[ "$df" == "$rel" ]]; then
            found=true
            break
        fi
    done
    if ! $found; then
        echo "  UNLISTED: $rel (has generation banner but not in .generated-files)"
        ((ERRORS++)) || true
    fi
done < <(grep -rl --include='*.md' -Z 'generated by.*scripts/' "$ROOT/docs" 2>/dev/null | \
    grep -v '/adr/' | grep -v '/compiler/diagnostics' | grep -v '/compiler/error-codes' || true)

if [[ $ERRORS -gt 0 ]]; then
    echo ""
    echo "Found $ERRORS generated-file boundary issue(s)."
    exit 1
else
    echo "✓ All generated files have banners and are listed in .generated-files"
fi
