// Component interop test fixture: jco-transpiled scalar assertions.
//
// This module imports the JS glue generated by `jco transpile` and asserts
// the calculator exports behave correctly. Because the T3 backend emits
// 64-bit Wasm memory, Node.js must be invoked with
// `--experimental-wasm-memory64`; `run.sh` takes care of this.
//
// String-returning exports (e.g. greet) are intentionally excluded:
// canonical ABI lift/lower for GC-native String is not yet implemented.

import { add, mul, negate } from './jco-out/calculator.component.js';

let pass = 0;
let fail = 0;

function assert_eq(desc, actual, expected) {
    if (actual === expected) {
        console.log(`      PASS: ${desc}`);
        pass += 1;
    } else {
        console.log(`      FAIL: ${desc} — expected '${expected}', got '${actual}'`);
        fail += 1;
    }
}

console.log('[1/2] Asserting scalar exports');
assert_eq('add(3, 4) = 7', add(3n, 4n), 7n);
assert_eq('add(0, 0) = 0', add(0n, 0n), 0n);
assert_eq('add(-1, 1) = 0', add(-1n, 1n), 0n);
assert_eq('mul(6, 7) = 42', mul(6n, 7n), 42n);
assert_eq('mul(0, 100) = 0', mul(0n, 100n), 0n);
assert_eq('negate(5) = -5', negate(5n), -5n);
assert_eq('negate(-3) = 3', negate(-3n), 3n);

console.log(`[2/2] Results: ${pass} passed, ${fail} failed`);
process.exit(fail > 0 ? 1 : 0);
