#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OPEN_DIR="$ROOT/issues/open"
INDEX_OUT="$OPEN_DIR/index.md"
GRAPH_OUT="$OPEN_DIR/dependency-graph.md"

python3 - "$OPEN_DIR" "$INDEX_OUT" "$GRAPH_OUT" <<'PY'
import re
import sys
from pathlib import Path
from collections import defaultdict, deque

open_dir = Path(sys.argv[1])
index_out = Path(sys.argv[2])
graph_out = Path(sys.argv[3])

issue_files = sorted(open_dir.glob('*.md'))
issues = {}
reverse = defaultdict(list)

meta_re = re.compile(r"^\*\*(.+?)\*\*: (.*)$")

for path in issue_files:
    text = path.read_text()
    lines = text.splitlines()
    title = lines[0][2:].strip() if lines and lines[0].startswith('# ') else path.stem
    meta = {}
    for line in lines[1:12]:
        m = meta_re.match(line)
        if m:
            meta[m.group(1).strip()] = m.group(2).strip()
    issue_id = meta.get('ID', path.name.split('-')[0])
    deps_raw = meta.get('Depends on', 'none')
    deps = [] if deps_raw == 'none' else [d.strip() for d in deps_raw.split(',') if d.strip()]
    status = meta.get('Status', 'open')
    track = meta.get('Track', 'main')
    blocks_v1 = meta.get('Blocks v1 exit', 'no')
    acceptance_unchecked = sum(1 for line in lines if line.startswith('- [ ]'))
    acceptance_checked = sum(1 for line in lines if line.startswith('- [x]') or line.startswith('- [X]'))
    issues[issue_id] = {
        'id': issue_id,
        'title': title,
        'path': path.name,
        'deps': deps,
        'status': status,
        'track': track,
        'blocks_v1': blocks_v1,
        'unchecked': acceptance_unchecked,
        'checked': acceptance_checked,
    }

for issue_id, data in issues.items():
    for dep in data['deps']:
        reverse[dep].append(issue_id)

# topological order among known deps
indegree = {iid: 0 for iid in issues}
for iid, data in issues.items():
    for dep in data['deps']:
        if dep in issues:
            indegree[iid] += 1
queue = deque(sorted([iid for iid, deg in indegree.items() if deg == 0]))
order = []
while queue:
    iid = queue.popleft()
    order.append(iid)
    for child in sorted(reverse.get(iid, [])):
        indegree[child] -= 1
        if indegree[child] == 0:
            queue.append(child)
if len(order) != len(issues):
    remaining = [iid for iid in issues if iid not in order]
    order.extend(sorted(remaining))

# index markdown
lines = []
lines.append('# Open Issues Index')
lines.append('')
lines.append('Auto-generated by `scripts/generate-issue-index.sh`. Do not edit manually.')
lines.append('')
lines.append('## Summary')
lines.append('')
lines.append(f'- Total open issues: {len(issues)}')
lines.append(f'- Main-track issues: {sum(1 for i in issues.values() if i["track"] == "main")}')
lines.append(f'- Parallel-track issues: {sum(1 for i in issues.values() if i["track"] == "parallel")}')
lines.append(f'- V1-exit blockers: {sum(1 for i in issues.values() if i["blocks_v1"] == "yes")}')
lines.append('')
lines.append('## Dependency order')
lines.append('')
for idx, iid in enumerate(order, 1):
    data = issues[iid]
    lines.append(f'{idx}. [{iid} — {data["title"]}]({data["path"]})')
lines.append('')
lines.append('## Issue table')
lines.append('')
lines.append('| ID | Title | Track | Blocks v1 | Depends on | Blocks | Acceptance | |')
lines.append('|----|-------|-------|-----------|------------|--------|------------|-|')
for iid in order:
    data = issues[iid]
    deps = ', '.join(data['deps']) if data['deps'] else 'none'
    blocks = ', '.join(sorted(reverse.get(iid, []))) if reverse.get(iid) else 'none'
    progress = f'{data["checked"]} checked / {data["unchecked"]} open'
    lines.append(f'| {iid} | [{data["title"]}]({data["path"]}) | {data["track"]} | {data["blocks_v1"]} | {deps} | {blocks} | {progress} | |')
index_out.write_text('\n'.join(lines) + '\n')

# graph markdown
mermaid = ['graph TD']
for iid in order:
    mermaid.append(f'  I{iid}["{iid} {issues[iid]["title"]}"]')
for iid in order:
    for dep in issues[iid]['deps']:
        if dep in issues:
            mermaid.append(f'  I{dep} --> I{iid}')

graph = []
graph.append('# Issue Dependency Graph')
graph.append('')
graph.append('Auto-generated by `scripts/generate-issue-index.sh`. Do not edit manually.')
graph.append('')
graph.append('## Mermaid graph')
graph.append('')
graph.append('```mermaid')
graph.extend(mermaid)
graph.append('```')
graph.append('')
graph.append('## Adjacency list')
graph.append('')
for iid in order:
    deps = ', '.join(issues[iid]['deps']) if issues[iid]['deps'] else 'none'
    blocks = ', '.join(sorted(reverse.get(iid, []))) if reverse.get(iid) else 'none'
    graph.append(f'- **{iid}** depends on: {deps}; blocks: {blocks}')

graph_out.write_text('\n'.join(graph) + '\n')
PY
